### ISSUE TITLE
Error: invalid code -- missing end-of-block while executing `npm i --save-dev deno-bin`

### ISSUE THREAD

**Issue by vazexqi** [kt3k/deno-bin#26]
Just started happening a few hours ago

npm i --save-dev deno-bin

```
171 error path /Users/vazexqi/Desktop/cli/node_modules/deno-bin
172 error command failed
173 error command sh -c node install.js
174 error node:internal/process/promises:288
174 error             triggerUncaughtException(err, true /* fromPromise */);
174 error             ^
174 error
174 error Error: invalid code -- missing end-of-block
174 error     at __node_internal_genericNodeError (node:internal/errors:865:15)
174 error     at Zlib.zlibOnError [as onerror] (node:zlib:189:17)
174 error     at processChunkSync (node:zlib:457:12)
174 error     at zlibBufferSync (node:zlib:178:12)
174 error     at Object.syncBufferWrapper [as inflateRawSync] (node:zlib:792:14)
174 error     at Object.inflate (/Users/vazexqi/Desktop/cli/node_modules/adm-zip/methods/inflater.js:6:25)
174 error     at decompress (/Users/vazexqi/Desktop/cli/node_modules/adm-zip/zipEntry.js:80:45)
174 error     at Object.getData (/Users/vazexqi/Desktop/cli/node_modules/adm-zip/zipEntry.js:268:24)
174 error     at Object.extractEntryTo (/Users/vazexqi/Desktop/cli/node_modules/adm-zip/adm-zip.js:552:32)
174 error     at main (/Users/vazexqi/Desktop/cli/node_modules/deno-bin/install.js:54:21) {
174 error   errno: -3,
174 error   code: 'Z_DATA_ERROR'
174 error }
174 error
174 error Node.js v18.18.2
```

**Comment by vazexqi** [comment]
I believe the issue is due to https://github.com/cthackers/adm-zip/releases (version 0.5.11) that was just released.
Once I lock it to 0.5.10 it works fine.

**Comment by kt3k** [comment]
Sorry for the late response, but it seems to be fixed in 0.5.12 already. Can you confirm it?
